# Generated by Django 2.2.1 on 2019-06-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190602_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
