# Generated by Django 2.2.1 on 2019-06-11 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190611_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 4, 54, 53, 704912)),
        ),
    ]
