# Generated by Django 2.2.1 on 2019-06-02 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.CreateModel(
            name='WishlistItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wishlist')),
            ],
        ),
    ]
