# Generated by Django 2.2.1 on 2019-06-11 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190611_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='customer',
        ),
        migrations.AlterField(
            model_name='coupons',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 5, 12, 31, 18016)),
        ),
    ]
