# Generated by Django 2.2.1 on 2019-06-03 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190602_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='product_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProductImage'),
        ),
    ]
