# Generated by Django 2.1.7 on 2019-06-04 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190603_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
    ]
