# Generated by Django 2.1.7 on 2019-06-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190604_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='product',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='image',
            field=models.FileField(default='product_images/default.jpg', upload_to='product_images/ordered_items/'),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
