# Generated by Django 2.1.7 on 2019-06-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190606_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
