# Generated by Django 2.1.7 on 2019-06-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='message',
            field=models.CharField(default='', max_length=250),
        ),
    ]
